.PHONY:all
hb:
	g++ -o hb.exe happybirthday.cc -lstdc++

cal:
	g++ -o cal.exe calculator.cc -lstdc++	

sav:
	g++ -o sav.exe save.cc -lstdc++

1st:clean
	g++ -o 1st.exe 1stweekworks.cc -DW1_5 -lstdc++

2nd:clean
	g++ -o 2nd.exe 2ndweekworks.cc -DW2_5 -lstdc++
	
clean:
	rm -f *.exe